pub enum Keyword {
    LET,
    FN,
    IF,
    ELSE,
    WHILE,
    RETURN,
    CONST,
    VAR,
    TYPE,
    PROXY,
    INTERFACE,
    CLASS,
    ABSTRACT,
    INHERITS,
    DERIVES,
    IMPLEMENTS,
    EXTENDS,
    MATCH,
    NAMESPACE,
    IMPORT,
    USE,
    WITH,
    NOT,
    TEST,
    STUB,
    MOCK,
    FAILS,
}

impl Keyword {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            | "let" => Some(Keyword::LET),
            | "fn" => Some(Keyword::FN),
            | "if" => Some(Keyword::IF),
            | "else" => Some(Keyword::ELSE),
            | "while" => Some(Keyword::WHILE),
            | "return" => Some(Keyword::RETURN),
            | "const" => Some(Keyword::CONST),
            | "var" => Some(Keyword::VAR),
            | "type" => Some(Keyword::TYPE),
            | "proxy" => Some(Keyword::PROXY),
            | "interface" => Some(Keyword::INTERFACE),
            | "class" => Some(Keyword::CLASS),
            | "abstract" => Some(Keyword::ABSTRACT),
            | "inherits" => Some(Keyword::INHERITS),
            | "derives" => Some(Keyword::DERIVES),
            | "implements" => Some(Keyword::IMPLEMENTS),
            | "extends" => Some(Keyword::EXTENDS),
            | "match" => Some(Keyword::MATCH),
            | "namespace" => Some(Keyword::NAMESPACE),
            | "import" => Some(Keyword::IMPORT),
            | "use" => Some(Keyword::USE),
            | "with" => Some(Keyword::WITH),
            | "not" => Some(Keyword::NOT),
            | "test" => Some(Keyword::TEST),
            | "stub" => Some(Keyword::STUB),
            | "mock" => Some(Keyword::MOCK),
            | "fails" => Some(Keyword::FAILS),
            | _ => None,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            | Keyword::LET => "let",
            | Keyword::FN => "fn",
            | Keyword::IF => "if",
            | Keyword::ELSE => "else",
            | Keyword::WHILE => "while",
            | Keyword::RETURN => "return",
            | Keyword::CONST => "const",
            | Keyword::VAR => "var",
            | Keyword::TYPE => "type",
            | Keyword::PROXY => "proxy",
            | Keyword::INTERFACE => "interface",
            | Keyword::CLASS => "class",
            | Keyword::ABSTRACT => "abstract",
            | Keyword::INHERITS => "inherits",
            | Keyword::DERIVES => "derives",
            | Keyword::IMPLEMENTS => "implements",
            | Keyword::EXTENDS => "extends",
            | Keyword::MATCH => "match",
            | Keyword::NAMESPACE => "namespace",
            | Keyword::IMPORT => "import",
            | Keyword::USE => "use",
            | Keyword::WITH => "with",
            | Keyword::NOT => "not",
            | Keyword::TEST => "test",
            | Keyword::STUB => "stub",
            | Keyword::MOCK => "mock",
            | Keyword::FAILS => "fails",
        }
    }
}
