pub enum Symbols {
    LeftParentheses,
    RightParentheses,
    LeftBracket,
    RightBracket,
    LeftBrace,
    RightBrace,
    Bar, // |
    Comma,
    Semicolon,
    Colon,
    Dot,
    Backslash,
    Underscore,
    AtSign,
    DashArrow,       // ->
    EqualArrow,      // =>
    Question,        // ?
    Bang,            // !
    CharDeclaration, // #\
    Curry,           // |>
    LAMBDA,          // λ (same as lambda in types)
    PLUS,
    PLUS_PLUS,
    MINUS,
    MINUS_MINUS,
    STAR,
    SLASH,
    POWER,
    PERCENT,
    OR,
    AND,
    OR_MATH,  // same as or,  but with the unicode symbol
    AND_MATH, // same as and, but with the unicode symbol
    XOR_MATH,
    EQUALS,
    NOT_EQUALS,
    EQUAL_EQUAL,
    LESS,    // also used in array, and structs
    GREATER, // ^------------------------------
    LESS_EQUAL,
    GREATER_EQUAL,
    PLUS_EQUAL,
    MINUS_EQUAL,
    STAR_EQUAL,
    SLASH_EQUAL,
    PERCENT_EQUAL,
}

impl Symbols {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            | "(" => Some(Symbols::LeftParentheses),
            | ")" => Some(Symbols::RightParentheses),
            | "[" => Some(Symbols::LeftBracket),
            | "]" => Some(Symbols::RightBracket),
            | "{" => Some(Symbols::LeftBrace),
            | "}" => Some(Symbols::RightBrace),
            | "|" => Some(Symbols::Bar),
            | "," => Some(Symbols::Comma),
            | ";" => Some(Symbols::Semicolon),
            | ":" => Some(Symbols::Colon),
            | "." => Some(Symbols::Dot),
            | "\\" => Some(Symbols::Backslash),
            | "_" => Some(Symbols::Underscore),
            | "@" => Some(Symbols::AtSign),
            | "->" => Some(Symbols::DashArrow),
            | "=>" => Some(Symbols::EqualArrow),
            | "?" => Some(Symbols::Question),
            | "!" => Some(Symbols::Bang),
            | "#\\" => Some(Symbols::CharDeclaration),
            | "|>" => Some(Symbols::Curry),
            | "λ" => Some(Symbols::LAMBDA),
            | "+" => Some(Symbols::PLUS),
            | "++" => Some(Symbols::PLUS_PLUS),
            | "-" => Some(Symbols::MINUS),
            | "--" => Some(Symbols::MINUS_MINUS),
            | "*" => Some(Symbols::STAR),
            | "/" => Some(Symbols::SLASH),
            | "**" => Some(Symbols::POWER),
            | "%" => Some(Symbols::PERCENT),
            | "||" => Some(Symbols::OR),
            | "&&" => Some(Symbols::AND),
            | "∨" => Some(Symbols::OR_MATH),
            | "∧" => Some(Symbols::AND_MATH),
            | "⊕" => Some(Symbols::XOR_MATH),
            | "=" => Some(Symbols::EQUALS),
            | "!=" => Some(Symbols::NOT_EQUALS),
            | "==" => Some(Symbols::EQUAL_EQUAL),
            | "<" => Some(Symbols::LESS),
            | ">" => Some(Symbols::GREATER),
            | "<=" => Some(Symbols::LESS_EQUAL),
            | ">=" => Some(Symbols::GREATER_EQUAL),
            | "+=" => Some(Symbols::PLUS_EQUAL),
            | "-=" => Some(Symbols::MINUS_EQUAL),
            | "*=" => Some(Symbols::STAR_EQUAL),
            | "/=" => Some(Symbols::SLASH_EQUAL),
            | "%=" => Some(Symbols::PERCENT_EQUAL),
            | _ => None,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            | Symbols::LeftParentheses => "(",
            | Symbols::RightParentheses => ")",
            | Symbols::LeftBracket => "[",
            | Symbols::RightBracket => "]",
            | Symbols::LeftBrace => "{",
            | Symbols::RightBrace => "}",
            | Symbols::Bar => "|",
            | Symbols::Comma => ",",
            | Symbols::Semicolon => ";",
            | Symbols::Colon => ":",
            | Symbols::Dot => ".",
            | Symbols::Backslash => "\\",
            | Symbols::Underscore => "_",
            | Symbols::AtSign => "@",
            | Symbols::DashArrow => "->",
            | Symbols::EqualArrow => "=>",
            | Symbols::Question => "?",
            | Symbols::Bang => "!",
            | Symbols::CharDeclaration => "#\\",
            | Symbols::Curry => "|>",
            | Symbols::LAMBDA => "λ",
            | Symbols::PLUS => "+",
            | Symbols::PLUS_PLUS => "++",
            | Symbols::MINUS => "-",
            | Symbols::MINUS_MINUS => "--",
            | Symbols::STAR => "*",
            | Symbols::SLASH => "/",
            | Symbols::POWER => "**",
            | Symbols::PERCENT => "%",
            | Symbols::OR => "||",
            | Symbols::AND => "&&",
            | Symbols::OR_MATH => "∨",
            | Symbols::AND_MATH => "∧",
            | Symbols::XOR_MATH => "⊕",
            | Symbols::EQUALS => "=",
            | Symbols::NOT_EQUALS => "!=",
            | Symbols::EQUAL_EQUAL => "==",
            | Symbols::LESS => "<",
            | Symbols::GREATER => ">",
            | Symbols::LESS_EQUAL => "<=",
            | Symbols::GREATER_EQUAL => ">=",
            | Symbols::PLUS_EQUAL => "+=",
            | Symbols::MINUS_EQUAL => "-=",
            | Symbols::STAR_EQUAL => "*=",
            | Symbols::SLASH_EQUAL => "/=",
            | Symbols::PERCENT_EQUAL => "%=",
        }
    }
}
