use crate::define_parsable_enum;

define_parsable_enum! {
    pub enum Keyword {
        Let => "let",
        Fn => "fn",
        If => "if",
        Else => "else",
        While => "while",
        Return => "return",
        Const => "const",
        Var => "var",
        Type => "type",
        Proxy => "proxy",
        Interface => "interface",
        Class => "class",
        Abstract => "abstract",
        Inherits => "inherits",
        Derives => "derives",
        Implements => "implements",
        Extends => "extends",
        Match => "match",
        Namespace => "namespace",
        Import => "import",
        Use => "use",
        With => "with",
        Not => "not",
        Test => "test",
        Stub => "stub",
        Mock => "mock",
        Fails => "fails",
        Inst => "inst",
        Priv => "priv",
        Static => "static",
        Prot => "prot",
        Override => "override",
        Lambda => "lambda",
        Overwrite => "overwrite",
        Pub => "pub",
        Until => "until",
        Underscore => "_",
    }
}
