use crate::define_parsable_enum;

define_parsable_enum! {
    pub enum Operator {
        Plus => "+",
        PlusPlus => "++",
        Minus => "-",
        MinusMinus => "--",
        Star => "*",
        Slash => "/",
        Power => "**",
        Percent => "%",
        Or => "||",
        And => "&&",
        OrMath => "∨",
        AndMath => "∧",
        XorMath => "⊕",
        Assignment => "=",
        NotEquals => "!=",
        EqualEqual => "==",
        Less => "<",
        Greater => ">",
        LessEqual => "<=",
        GreaterEqual => ">=",
        PlusEqual => "+=",
        MinusEqual => "-=",
        StarEqual => "*=",
        SlashEqual => "/=",
        PercentEqual => "%=",
        Pipe => "|>",
        PowerEqual => "**=",
        CharDeclaration => "#\\",
        DashArrow => "->",
        Backslash => "\\",
        EqualArrow => "=>",
        Hashtag => "#",
        AtSign => "@",
    }
}
